/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pascualbravo.citadel.views;

import com.pascualbravo.citadel.controllers.UnitsController;
import com.pascualbravo.citadel.models.Book;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HIGUITA
 */
public class FormUnits extends javax.swing.JDialog {

    private static FormUnits instance = null;
    private UnitsController unitsController;
    private int dialogResult;
    private int bookId;
    
    private FormUnits(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        unitsController = UnitsController.getInstance();
    }
    
    public static FormUnits getInstance(){
        if(instance == null){
            instance = new FormUnits(new javax.swing.JFrame(), true);
        }
        return instance;
    }
    
    public int getDialogResult(){
        return this.dialogResult;
    }
    
    public void setBookId(int bookId){
        this.bookId = bookId;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUnits = new java.awt.Label();
        txtUnits = new javax.swing.JTextField();
        btnCancel = new java.awt.Button();
        btnTrolley = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblUnits.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUnits.setText("Unidades");

        txtUnits.setText("1");

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancel.setLabel("Cancelar");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnTrolley.setBackground(new java.awt.Color(59, 86, 140));
        btnTrolley.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrolley.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTrolley.setForeground(new java.awt.Color(255, 255, 255));
        btnTrolley.setLabel("Agregar");
        btnTrolley.setName("btnTrolley"); // NOI18N
        btnTrolley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrolleyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTrolley, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrolley, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       dialogResult=0;
       txtUnits.setText("1");
       this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnTrolleyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrolleyActionPerformed

       try{
           String errorMessage = unitsController.validateData(txtUnits.getText());
           
           if(!errorMessage.isEmpty()){
               JOptionPane.showMessageDialog(null, errorMessage);
               return;
           }
           Book book = unitsController.getBookByBookId(bookId);
           if(book == null){
                JOptionPane.showMessageDialog(null, "El libro no existe");
                return;
           }
           
           if(unitsController.getExistByBookId(bookId)){
               JOptionPane.showMessageDialog(null, "El libro ya existe en el carrito");
                return;
           }
           
           if(Integer.parseInt(txtUnits.getText())>book.getUnits()){
               JOptionPane.showMessageDialog(null, "Las unidades escritas son mayores a las registradas");
               return;
           }
           
           unitsController.createTrolley(bookId, txtUnits.getText());
           
           dialogResult=1;
           txtUnits.setText("1");
           this.dispose();           
       }catch(SQLException ex){
           System.out.println(ex);
       }
       
    }//GEN-LAST:event_btnTrolleyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCancel;
    private java.awt.Button btnTrolley;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label lblUnits;
    private javax.swing.JTextField txtUnits;
    // End of variables declaration//GEN-END:variables
}
