/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pascualbravo.citadel.views.panels;

import com.pascualbravo.citadel.controllers.SaleController;
import com.pascualbravo.citadel.views.DialogRegisterSale;
import java.sql.SQLException;

/**
 *
 * @author HIGUITA
 */
public class PanelSale extends javax.swing.JPanel {

    /**
     * Creates new form panelSale
     */
    private SaleController saleController;
    private DialogRegisterSale dialogRegisterSale;
    public PanelSale() {
        initComponents();
        dialogRegisterSale = DialogRegisterSale.getInstance();
        saleController = SaleController.getInstance();
        loadSale();
    }
    
    private void loadSale(){
        try{
            saleController.loadSale(tableSale);
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollSale = new javax.swing.JScrollPane();
        tableSale = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("panelSale"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1320, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Ventas");

        scrollSale.setName("scrollSale"); // NOI18N

        tableSale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSale.setName("tableSale"); // NOI18N
        tableSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSaleMouseClicked(evt);
            }
        });
        scrollSale.setViewportView(tableSale);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollSale, javax.swing.GroupLayout.PREFERRED_SIZE, 1305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(586, 586, 586)
                        .addComponent(jLabel1)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(scrollSale, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("panelSale");
    }// </editor-fold>//GEN-END:initComponents

    private void tableSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSaleMouseClicked
        int row = saleController.buttonTableSale(tableSale, evt);
        
        if(row != -1){
            int saleId = Integer.parseInt(tableSale.getValueAt(row, 0).toString());
            dialogRegisterSale.setSaleId(saleId);
            dialogRegisterSale.loadRegisterSale();
            dialogRegisterSale.setVisible(true);
        }
    }//GEN-LAST:event_tableSaleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollSale;
    private javax.swing.JTable tableSale;
    // End of variables declaration//GEN-END:variables
}
